# --- CONFIGURACIÓN GLOBAL ---
HOME_DOMAIN = "ernestocripto.github.io"

ACCOUNTS = [
  "GAVOA6QBBSDKH3NMD2LQIJBXBT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6"
]

[DOCUMENTATION]
ORG_NAME = "Skill Graph"
ORG_URL = "https://ernestocripto.github.io"
ORG_DESCRIPTION = "Plataforma de emisión de insignias SBT."

[[CURRENCIES]]
code = "MKT101"
issuer = "GAVOA6QBBSDKH3NMD2LQIJBXBT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6"
display_decimals = 0
name = "Bootcamp de Marketing"
desc = "Insignia otorgada por completar las 20 horas del bootcamp Marketing para Blockchain"
image = "https://github.com/ErnestoCripto/SkillGraph/blob/main/assets/MKT101.png?raw=true"
conditions = "SBT - No transferible"
