# --- CONFIGURACIÓN GLOBAL ---
# El dominio donde está alojado este archivo (sin https://)
HOME_DOMAIN = "ErnestoCritpo.github.io"

# Cuentas vinculadas a este dominio
ACCOUNTS = [
  "GAVOA6QBBSDKH3NMD2LQIJBXBT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6" # Tu Public Key Emisora (la misma para todos los assets)
]

[DOCUMENTATION]
ORG_NAME = "Skill Graph"
ORG_URL = "[https://ErnestoCripto.github.io/](https://ErnestoCripto.github.io/SkillGraph)"
ORG_DESCRIPTION = "Plataforma de emisión de insignias Soulbound (SBT) para diversos cursos y eventos."
ORG_LOGO = "[https://ErnestoCritpo.github.io/SkillGraph/logo.png](https://ErnestoCripto.github.io/SkillGraph/logo.png)"

# --- LISTA DE INSIGNIAS (CURRENCIES) ---

# Insignia 1: Introducción a Stellar
[[CURRENCIES]]
code = "STELLAR101"
issuer = "GAVOA6QBBSDKH3NMD2LQIJBXT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6"
display_decimals = 0
name = "Stellar Fundamentals"
desc = "Insignia otorgada por completar el nivel basico de Stellar."
image="https://raw.githubusercontent.com/ErnestoCripto/SkillGraph/main/assets/STELLAR101.png"
conditions = "SBT - No transferible"

# Insignia 2: Bootcamp de Marketing Web3
[[CURRENCIES]]
code = "MKT101"
issuer = "GAVOA6QBBSDKH3NMD2LQIJBXBT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6"
display_decimals = 0
name = "Marketing Web3 Bootcamp"
desc = "Certificado de participación en el bootcamp de Marketing Web3."
image = "https://ernestocripto.github.io/SkillGraph/assets/MKT101.png"
conditions = "SBT - No transferible"

# Insignia 3: Talk Cripto Monedas
[[CURRENCIES]]
code = "CRIPTO01"
issuer = "GAVOA6QBBSDKH3NMD2LQIJBXBT3CZPG4CHFGMNDZ4PJ63T7XVK5VKGF6"
display_decimals = 0
image = "https://raw.githubusercontent.com/ErnestoCripto/SkillGraph/main/assets/CRIPTO01.png?raw=true"
name = "Cripto Monedas UTEZ"
desc = "Reconocimiento por participar en la Talk Cripto Monedas."
